routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::model('town', 'App\Town');
Route::model('apartment_check', 'App\ApartmentCheck');

/**
 * Main Route Group
 */
Route::group([], function(){

    /**
     * Public Routes
     */
    // ...

    /**
     * Only Authenticated Users Routes
     */
    Route::group(["middleware" => "auth"], function(){

        // Dashboard Route
        Route::get("/", ["as" => "dashboard.index", "uses" => "DashboardController@index"]);

        /**
         * 'Actions' permission routes
         */
        Route::group(['middleware' => ['permission:actions*'], "prefix" => "action", "as" => "actions.", "namespace" => "Action"], function(){

            // 'Actions Create' route for multiple create actions.
            Route::get('create', ["as" => "create", "middleware" => ['permission:actions.create'], "uses" => "ActionsController@create"]);
            Route::post('create', ["as" => "store", "middleware" => ['permission:actions.create'], "uses" => "ActionsController@store"]);

            /**
             * 'Apartment Actions' permission routes
             */
            Route::group(['middleware' => ['permission:actions.apartment*'], 'prefix' => "apartment", "as" => "apartment."], function(){

                Route::get('/',                  ["as" => "index",   "uses" => "ApartmentController@index"]);
                Route::get("create",             ["as" => "create",  "uses" => "ApartmentController@create",  "middleware" => "permission:actions.apartment.create"]);
                Route::post("/",                 ["as" => "store",   "uses" => "ApartmentController@store",   "middleware" => "permission:actions.apartment.create"]);
                Route::get("{apartment}",        ["as" => "show",    "uses" => "ApartmentController@show"]);
                Route::delete("multi-delete",   ["as" => "destroyMulti", "uses" => "ApartmentController@destroyMultiple"]);
                Route::get("{apartment}/edit",   ["as" => "edit",    "uses" => "ApartmentController@edit",    "middleware" => "permission:actions.apartment.edit"]);
                Route::put("{apartment}",        ["as" => "update",  "uses" => "ApartmentController@update",  "middleware" => "permission:actions.apartment.edit"]);
                Route::get("{apartment}/delete", ["as" => "destroy", "uses" => "ApartmentController@destroy", "middleware" => "permission:actions.apartment.delete"]);

                Route::group(["middleware" => ['permission:actions.apartment.check*'], "prefix" => "{apartment}/check", "as" => "check."], function(){
                    Route::get('/',                  ["as" => "index",   "uses" => "ApartmentCheckController@index"]);
                    Route::get("create",             ["as" => "create",  "uses" => "ApartmentCheckController@create",  "middleware" => "permission:actions.apartment.create"]);
                    Route::post("/",                 ["as" => "store",   "uses" => "ApartmentCheckController@store",   "middleware" => "permission:actions.apartment.create"]);
                    Route::get("{apartment_check}",        ["as" => "show",    "uses" => "ApartmentCheckController@show"]);
                    Route::delete("multi-delete",   ["as" => "destroyMulti", "uses" => "ApartmentCheckController@destroyMultiple"]);
                    Route::get("{apartment_check}/edit",   ["as" => "edit",    "uses" => "ApartmentCheckController@edit",    "middleware" => "permission:actions.apartment.edit"]);
                    Route::put("{apartment_check}",        ["as" => "update",  "uses" => "ApartmentCheckController@update",  "middleware" => "permission:actions.apartment.edit"]);
                    Route::get("{apartment_check}/delete", ["as" => "destroy", "uses" => "ApartmentCheckController@destroy", "middleware" => "permission:actions.apartment.delete"]);
                });

            });

            /**
             * 'Home Actions' permission routes
             */
            Route::group(['middleware' => ['permission:actions.home*'], 'prefix' => "home", "as" => "home."], function(){

                Route::get('/',             ["as" => "index",   "uses" => "HomeController@index"]);
                Route::get("create",        ["as" => "create",  "uses" => "HomeController@create",  "middleware" => "permission:actions.home.create"]);
                Route::post("/",            ["as" => "store",   "uses" => "HomeController@store",   "middleware" => "permission:actions.home.create"]);
                Route::delete("multi-delete",   ["as" => "destroyMulti", "uses" => "HomeController@destroyMultiple", "middleware" => "permission:actions.home.delete"]);
                Route::get("{home}",        ["as" => "show",    "uses" => "HomeController@show"]);
                Route::get("{home}/edit",   ["as" => "edit",    "uses" => "HomeController@edit",    "middleware" => "permission:actions.home.edit"]);
                Route::put("{home}",        ["as" => "update",  "uses" => "HomeController@update",  "middleware" => "permission:actions.home.edit"]);
                Route::get("{home}/delete", ["as" => "destroy", "uses" => "HomeController@destroy", "middleware" => "permission:actions.home.delete"]);

            });

            /**
             * 'Sell Actions' permission routes
             */
            Route::group(['middleware' => ['permission:actions.sell*'], 'prefix' => "sell", "as" => "sell."], function(){

                Route::get('/',             ["as" => "index",   "uses" => "SellController@index"]);
                Route::get("create",        ["as" => "create",  "uses" => "SellController@create",  "middleware" => "permission:actions.sell.create"]);
                Route::post("/",            ["as" => "store",   "uses" => "SellController@store",   "middleware" => "permission:actions.sell.create"]);
                Route::delete("multi-delete",   ["as" => "destroyMulti", "uses" => "SellController@destroyMultiple", "middleware" => "permission:actions.sell.delete"]);
                Route::get("{sell}",        ["as" => "show",    "uses" => "SellController@show"]);
                Route::get("{sell}/edit",   ["as" => "edit",    "uses" => "SellController@edit",    "middleware" => "permission:actions.sell.edit"]);
                Route::put("{sell}",        ["as" => "update",  "uses" => "SellController@update",  "middleware" => "permission:actions.sell.edit"]);
                Route::get("{sell}/delete", ["as" => "destroy", "uses" => "SellController@destroy", "middleware" => "permission:actions.sell.delete"]);

            });

            Route::group(["as" => "util.", "prefix" => "util"], function(){
                Route::get('apartments', ["as" => "apartments", "uses" => "UtilController@apartments"]);
                Route::get('options', ['as' => 'options', "uses" => "UtilController@options"]);
            });
        });

        /**
         * 'List' permission routes
         */
        Route::group(['middleware' => ['permission:list*'], "prefix" => "list", "as" => "list.", "namespace" => "Index"], function(){

            /**
             * 'Apartment List' permission routes
             */
            Route::group(['middleware' => ['permission:list.apartment*'], 'prefix' => "apartment", "as" => "apartment."], function(){

                Route::get('/',                  ["as" => "index",   "uses" => "ApartmentController@index"]);
                Route::get("{apartment}",        ["as" => "show",    "uses" => "ApartmentController@show"]);
                Route::get("{apartment}/edit",   ["as" => "edit",    "uses" => "ApartmentController@edit",    "middleware" => "permission:list.apartment.edit"]);
                Route::put("{apartment}",        ["as" => "update",  "uses" => "ApartmentController@update",  "middleware" => "permission:list.apartment.edit"]);
                Route::get("{apartment}/delete", ["as" => "destroy", "uses" => "ApartmentController@destroy", "middleware" => "permission:list.apartment.delete"]);

                Route::group(["middleware" => ['permission:list.apartment.check*'], "prefix" => "{apartment}/check", "as" => "check."], function(){
                    Route::get('/',                 ["as" => "index",   "uses" => "ApartmentCheckController@index"]);
                    Route::get("{apartment_check}", ["as" => "show",    "uses" => "ApartmentCheckController@show"]);
                });

            });

            /**
             * 'Home List' permission routes
             */
            Route::group(['middleware' => ['permission:list.home*'], 'prefix' => "home", "as" => "home."], function(){

                Route::get('/',             ["as" => "index",   "uses" => "HomeController@index"]);
                Route::get("{home}",        ["as" => "show",    "uses" => "HomeController@show"]);
                Route::get("{home}/edit",   ["as" => "edit",    "uses" => "HomeController@edit",    "middleware" => "permission:list.home.edit"]);
                Route::put("{home}",        ["as" => "update",  "uses" => "HomeController@update",  "middleware" => "permission:list.home.edit"]);
                Route::get("{home}/delete", ["as" => "destroy", "uses" => "HomeController@destroy", "middleware" => "permission:list.home.delete"]);

            });

            /**
             * 'Sell List' permission routes
             */
            Route::group(['middleware' => ['permission:list.sell*'], 'prefix' => "sell", "as" => "sell."], function(){

                Route::get('/',             ["as" => "index",   "uses" => "SellController@index"]);

app/Apartment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Apartment extends Model
{

    public function district()
    {
        return $this->belongsTo('App\District');
    }

    public function street()
    {
        return $this->belongsTo('App\Street');
    }

    public function town()
    {
        return $this->belongsTo('App\Town');
    }

    public function getAttachedStreetAttribute()
    {
        if($this->street)
            return $this->street;
        elseif($this->district)
            return $this->district->street;
        else
            return null;
    }

    public function getAttachedTownAttribute()
    {
        if($this->town)
            return $this->town;
        elseif($this->attachedStreet)
            return $this->attachedStreet->town;
        elseif($this->district)
            return $this->district->street->town;
        else
            return null;
    }

    public function checks()
    {
        return $this->hasMany('App\ApartmentCheck');
    }

    public function user_checks()
    {
        return $this->checks()->where('user_id', auth()->user()->id);
    }

    public function homes()
    {
        return $this->hasMany('App\Home');
    }

}

app/Http/Controllers/Action/ApartmentController.php
<?php

namespace App\Http\Controllers\Action;

use App\Apartment;
use App\Http\Requests\Action\ApartmentCreateRequest;
use App\Http\Requests\Action\ApartmentDestroyMultipleRequest;
use App\Http\Requests\Action\ApartmentEditRequest;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ApartmentController extends Controller
{
    public function index()
    {
        $apartments = Apartment::latest()->paginate(20);
        return view('action.apartment.index', [
            'apartments' => $apartments
        ]);
    }

    public function create()
    {
        return view('action.apartment.create');
    }

    public function store(ApartmentCreateRequest $request) {
        $apartment = new Apartment();
        if($request->get('district_id') != "not")
            $apartment->district_id = $request->get('district_id');
        if($request->get('street_id') != "not")
            $apartment->street_id = $request->get('street_id');
        if($request->get('town_id') != "not")
            $apartment->town_id = $request->get('town_id');
        $apartment->name = $request->get('name');
        $apartment->visor_name = $request->get('visor_name');
        $apartment->visor_surname = $request->get('visor_surname');
        $apartment->visor_phone = $request->get('visor_phone');
        $apartment->save();

        return redirect()->route('actions.apartment.index');
    }

    public function edit(Apartment $apartment) {
        return view('action.apartment.edit', [
            "apartment" => $apartment,
        ]);
    }

    public function update(ApartmentEditRequest $request, Apartment $apartment) {
        if($request->get('district_id') != "not")
            $apartment->district_id = $request->get('district_id');
        if($request->get('street_id') != "not")
            $apartment->street_id = $request->get('street_id');
        if($request->get('town_id') != "not")
            $apartment->town_id = $request->get('town_id');
        $apartment->name = $request->get('name');
        $apartment->visor_name = $request->get('visor_name');
        $apartment->visor_surname = $request->get('visor_surname');
        $apartment->visor_phone = $request->get('visor_phone');
        $apartment->save();

        return redirect()->route('actions.apartment.index');
    }

    public function destroy(Apartment $apartment)
    {
        $apartment->delete();

        return redirect()->back();
    }

    public function destroyMultiple(ApartmentDestroyMultipleRequest $request)
    {
        $result = [];

        foreach($request->get('select') as $selected){
            $apartment = Apartment::findOrFail($selected);
            $apartment->delete();
        }

        $result["status"] = true;

        return $result;
    }
}

app/Http/Controllers/Index/ApartmentController.php
<?php

namespace App\Http\Controllers\Index;

use App\Apartment;
use App\District;
use App\Street;
use App\Town;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ApartmentController extends Controller
{
    public function index(Request $request)
    {
        $townId     = $request->get('town_id');
        $streetId   = $request->get('street_id');
        $districtId = $request->get('district_id');

        $apartments = Apartment::latest();

        $town = Town::find($townId);
        if($town){
            $street = Street::find($streetId);
            if($street){
                $district = District::find($districtId);
                if($district){
                    $apartments = $apartments->where('district_id', $district->id);
                } else {
                    $apartments = $apartments->where('street_id', $street->id);
                }
            } else {
                $apartments = $apartments->where('town_id', $town->id);
            }
        }

        $apartments = $apartments->paginate(20);
        return view('index.apartment.index', [
            "apartments" => $apartments,

            "townId" => $townId,
            "streetId" => $streetId,
            "districtId" => $districtId,
        ]);
    }
}

resources/views/action/apartment/check/create.blade.php
@extends('layout.page')

@section('title', $apartment->name." - Giriş Oluşturma")

@section('page')
    <!-- BEGIN PAGE HEADER-->
    <!-- BEGIN PAGE BAR -->
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <a href="{{ url('/') }}">{{ config('app.name') }}</a>
                <i class="fa fa-circle"></i>
            </li>
            <li>
                <a href="{{ route('actions.apartment.index') }}">Apartmanlar</a>
                <i class="fa fa-circle"></i>
            </li>
            <li>
                <a href="{{ route('actions.apartment.check.index', $apartment->id) }}">{{ $apartment->name }} Girişleri</a>
                <i class="fa fa-circle"></i>
            </li>
            <li>
                <span>Yeni Giriş</span>
            </li>
        </ul>
    </div>
    <!-- END PAGE BAR -->
    <!-- END PAGE HEADER-->
<br>
    <!-- BEGIN TABLE -->
    <div class="row">
        <div class="col-md-12">
            <div class="portlet light bordered">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="icon-social-dribbble font-green"></i>
                        <span class="caption-subject font-green bold uppercase">Yeni Giriş Ekle</span>
                    </div>
                </div>
                <div class="portlet-body">
                    {!! Form::open(["route" => ["actions.apartment.check.store", $apartment->id], "method" => "POST", "files" => true]) !!}

                    @include("util.error")

                    <h4 style="margin-top: 0;">Seçenekler</h4>
                    @foreach(\App\CheckOption::all() as $option)
                        <div class="form-group">
                            <label>
                                {!! Form::checkbox('option['.$option->id.']', $option->id, old('option.'.$option->id), ["class" => "form-control"]) !!}
                                {{ $option->name }}
                            </label>
                        </div>
                    @endforeach

                    <div class="form-group">
                        {!! Form::label('pictures', "Resimler", ["class" => "control-label"]) !!}
                        <div class="input-icon">
                            <i class="fa fa-file fa-fw"></i>
                            {!! Form::file('pictures[]', ["class" => "form-control", "multiple"]) !!}
                        </div>
                    </div>

                    <div class="form-group">
                        {!! Form::label('notes', "Notlar", ["class" => "control-label"]) !!}
                        <div class="input-icon">
                            <i class="fa fa-pencil fa-fw"></i>
                            {!! Form::textarea('notes', old('notes'), ["class" => "form-control", "placeholder" => "Apartman ile ilgili bilgi notu giriniz."]) !!}
                        </div>
                    </div>

                    <div class="form-group text-center">
                        {!! Form::button('Giriş Kaydet <i class="fa fa-plus fa-fw"></i>', ["class" => "btn btn-success", "type" => "submit"]) !!}
                    </div>

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
    <!-- END TABLE -->
@stop

@section('page.js')
    @parent
    <script src="{{ asset('assets/pages/scripts/location-wizard.js') }}"></script>
@stop

resources/views/action/apartment/check/index.blade.php
@extends('layout.page')

@section('title', $apartment->name." Apartmanı Girişleri")

@section('page')
    <!-- BEGIN PAGE HEADER-->
    <!-- BEGIN PAGE BAR -->
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <a href="{{ url('/') }}">{{ config('app.name') }}</a>
                <i class="fa fa-circle"></i>
            </li>
            <li>
                <a href="{{ route('actions.apartment.index') }}">Apartmanlar</a>
                <i class="fa fa-circle"></i>
            </li>
            <li>
                <span>{{ $apartment->name }} Girişlerim</span>
            </li>
        </ul>
    </div>
    <!-- END PAGE BAR -->
    <!-- END PAGE HEADER-->
    <br>
    <!-- BEGIN TABLE -->
    <div class="row">
        <div class="col-md-12">
            <div class="portlet light bordered">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="icon-social-dribbble font-green"></i>
                        <span class="caption-subject font-green bold uppercase">{{ $apartment->name }} Girişlerim</span>
                    </div>
                    <div class="actions">
                        @if($checks->count() > 0)
                            @permission('actions.apartment.check.delete')
                            <button type="button" class="btn red btn-outline btn-delete-all" data-url="{{ route('actions.apartment.check.destroyMulti', $apartment->id) }}">
                                <i class="icon-trash"></i>
                                <span class="hidden-480">Seçilileri Sil</span>
                            </button>
                            @endpermission
                        @endif
                        @permission('actions.apartment.check.create')
                        <a class="btn green btn-outline" href="{{ route('actions.apartment.check.create', $apartment->id) }}">
                            <i class="icon-plus"></i>
                            <span class="hidden-480">Yeni Giriş Ekle</span>
                        </a>
                        @endpermission
                    </div>
                </div>
                <div class="portlet-body">
                    @if($checks->count() > 0)
                        <div class="table-scrollable">
                            <table class="table table-hover table-bordered">
                                <thead>
                                <tr>
                                    @permission('actions.apartment.check.delete')
                                    <th width="7%">
                                        <label class="table-select-label">
                                            <input type="checkbox" name="selectAll" class="table-select-all">
                                            <span class="hidden-480">Tümünü Seç</span>
                                        </label>
                                    </th>
                                    @endpermission
                                    <th width="5%"> # </th>
                                    <th width="20%"> Giriş Tarihi </th>
                                    <th> Fotoğraf Sayısı </th>
                                    @if(auth()->user()->can('actions.apartment.check.edit') || auth()->user()->can('actions.apartment.check.delete') || auth()->user()->can('actions.apartment.check.show'))
                                        <th width="45%">İşlemler</th>
                                    @endif
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($checks as $i => $check)
                                    <tr>
                                        @permission('actions.apartment.check.delete')
                                        <td><input type="checkbox" name="select[]" value="{{ $check->id }}" class="table-select"></td>
                                        @endpermission
                                        <td> {{ $i+1 }} </td>
                                        <td>
                                            {{ $check->created_at->format("d.m.Y H:i") }}
                                        </td>
                                        <td>
                                            <span class="label label-info">
                                                <i class="fa fa-photo"></i>
                                                {{ $check->pictures->count() }}
                                                <span class="hidden-480">Fotoğraf</span>
                                            </span>
                                        </td>
                                        @if(auth()->user()->can('actions.apartment.check.edit') || auth()->user()->can('actions.apartment.check.delete') || auth()->user()->can('actions.apartment.check.show'))
                                        <td>
                                            @permission('actions.apartment.check.show')
                                            <a href="{{ route('actions.apartment.check.show', [$apartment->id, $check->id]) }}" class="btn blue btn-sm btn-outline sbold uppercase">
                                                <i class="fa fa-eye"></i> <span class="hidden-480">Görüntüle</span>
                                            </a>
                                            @endpermission

                                            @if(!$check->isLocked)
                                                @permission('actions.apartment.check.edit')
                                                <a href="{{ route('actions.apartment.check.edit', [$apartment->id, $check->id]) }}" class="btn yellow btn-sm btn-outline sbold uppercase">
                                                    <i class="fa fa-pencil"></i> <span class="hidden-480">Düzenle</span>
                                                </a>
                                                @endpermission

                                                @permission('actions.apartment.check.delete')
                                                <a href="{{ route('actions.apartment.check.destroy', [$apartment->id, $check->id]) }}" class="btn red btn-sm btn-outline sbold uppercase delete-confirm">
                                                    <i class="fa fa-trash"></i> <span class="hidden-480">Sil</span>
                                                </a>
                                                @endpermission
                                            @endif
                                        </td>
                                        @endif
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    @else
                        <div class="alert alert-danger">
                            <p>
                                Henüz bir giriş oluşturulmadı.
                                @permission('actions.apartment.check.create')
                                Yeni bir <a href="{{ route('actions.apartment.check.create', $apartment->id) }}">giriş oluştur</a>abilirsiniz.
                                @endpermission
                            </p>
                        </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
    <!-- END TABLE -->
@stop

@section('plugin.js')
    @parent
    <script src="{{ asset('assets/global/plugins/bootbox/bootbox.min.js') }}" type="text/javascript"></script>
@stop

@section('page.js')
    @parent
    <script src="{{ asset('assets/pages/scripts/table-wizard.js') }}"></script>
@stop

resources/views/action/apartment/check/show.blade.php
@extends('layout.page')

@section('title', $apartment->name." - ".$check->created_at->format('d.m.Y H:i')." Tarihli Giriş")

@section('page')
    <!-- BEGIN PAGE HEADER-->
    <!-- BEGIN PAGE BAR -->
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <a href="{{ url('/') }}">{{ config('app.name') }}</a>
                <i class="fa fa-circle"></i>
            </li>
            <li>
                <a href="{{ route('actions.apartment.index') }}">Apartmanlar</a>
                <i class="fa fa-circle"></i>
            </li>
            <li>
                <a href="{{ route('actions.apartment.check.index', $apartment->id) }}">{{ $apartment->name }} Girişleri</a>
                <i class="fa fa-circle"></i>
            </li>
            <li>
                <span>{{ $apartment->name." - ".$check->created_at->format('d.m.Y H:i')." Tarihli Giriş" }}</span>
            </li>
        </ul>
    </div>
    <!-- END PAGE BAR -->
    <!-- END PAGE HEADER-->
<br>
    <!-- BEGIN TABLE -->
    <div class="row">
        <div class="col-md-12">
            <div class="portlet light bordered">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="icon-social-dribbble font-green"></i>
                        <span class="caption-subject font-green bold uppercase">
{{ $apartment->name." - ".$check->created_at->format('d.m.Y H:i')." Tarihli Giriş" }}
@permission('actions.apartment.delete')
<a href="{{ route('actions.apartment.check.destroy', [$apartment->id, $check->id]) }}" class="btn btn-danger btn-xs">Sil</a>
@endpermission
</span>
                    </div>
                </div>
                <div class="portlet-body">
                    <h4>Bilgiler</h4>
                    <table class="table table-striped table-hover table-bordered">
                        <thead>
                        <tr>
                            <th width="10%"></th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td>Tarih</td>
                            <td>{{ $check->created_at->format('d.m.Y H:i') }}</td>
                        </tr>
                        <tr>
                            <td>Personel</td>
                            <td>{{ $check->user->displayName }}</td>
                        </tr>
                        <tr>
                            <td>Notlar</td>
                            <td>{!! nl2br($check->notes) !!}</td>
                        </tr>
                        @if($check->options->count() > 0)
                        <tr>
                            <td>Seçenekler</td>
                            <td>
                                @foreach($check->options as $option)
                                    <div class="form-group">
                                        <label>
                                            <input type="checkbox" checked disabled>
                                            {{ $option->name }}
                                        </label>
                                    </div>
                                @endforeach
                            </td>
                        </tr>
                        @endif
                        </tbody>
                    </table>

                    @if($check->pictures->count() > 0)
                        <h4>Fotoğraflar</h4>
                        <div class="row">
                            @foreach($check->pictures as $picture)
                                <div class="col-md-4">
                                    <a title="{{ $picture->name }}" href="{{ asset($picture->file) }}" target="_blank">
                                        <img src="{{ asset($picture->file) }}" class="img-thumbnail img-responsive" style="height: 220px; max-width: 100%;">
                                    </a>
                                </div>
                            @endforeach
                        </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
    <!-- END TABLE -->
@stop

@section('page.js')
    @parent
    <script src="{{ asset('assets/pages/scripts/location-wizard.js') }}"></script>
@stop