routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::model('town', 'App\Town');
Route::model('apartment_check', 'App\ApartmentCheck');

/**
 * Main Route Group
 */
Route::group([], function(){

    /**
     * Public Routes
     */
    // ...

    /**
     * Only Authenticated Users Routes
     */
    Route::group(["middleware" => "auth"], function(){

        // Dashboard Route
        Route::get("/", ["as" => "dashboard.index", "uses" => "DashboardController@index"]);

        /**
         * 'Actions' permission routes
         */
        Route::group(['middleware' => ['permission:actions*'], "prefix" => "action", "as" => "actions.", "namespace" => "Action"], function(){

            // 'Actions Create' route for multiple create actions.
            Route::get('create', ["as" => "create", "middleware" => ['permission:actions.create'], "uses" => "ActionsController@create"]);
            Route::post('create', ["as" => "store", "middleware" => ['permission:actions.create'], "uses" => "ActionsController@store"]);

            /**
             * 'Apartment Actions' permission routes
             */
            Route::group(['middleware' => ['permission:actions.apartment*'], 'prefix' => "apartment", "as" => "apartment."], function(){

                Route::get('/',                  ["as" => "index",   "uses" => "ApartmentController@index"]);
                Route::get("create",             ["as" => "create",  "uses" => "ApartmentController@create",  "middleware" => "permission:actions.apartment.create"]);
                Route::post("/",                 ["as" => "store",   "uses" => "ApartmentController@store",   "middleware" => "permission:actions.apartment.create"]);
                Route::get("{apartment}",        ["as" => "show",    "uses" => "ApartmentController@show"]);
                Route::delete("multi-delete",   ["as" => "destroyMulti", "uses" => "ApartmentController@destroyMultiple"]);
                Route::get("{apartment}/edit",   ["as" => "edit",    "uses" => "ApartmentController@edit",    "middleware" => "permission:actions.apartment.edit"]);
                Route::put("{apartment}",        ["as" => "update",  "uses" => "ApartmentController@update",  "middleware" => "permission:actions.apartment.edit"]);
                Route::get("{apartment}/delete", ["as" => "destroy", "uses" => "ApartmentController@destroy", "middleware" => "permission:actions.apartment.delete"]);

                Route::group(["middleware" => ['permission:actions.apartment.check*'], "prefix" => "{apartment}/check", "as" => "check."], function(){
                    Route::get('/',                  ["as" => "index",   "uses" => "ApartmentCheckController@index"]);
                    Route::get("create",             ["as" => "create",  "uses" => "ApartmentCheckController@create",  "middleware" => "permission:actions.apartment.create"]);
                    Route::post("/",                 ["as" => "store",   "uses" => "ApartmentCheckController@store",   "middleware" => "permission:actions.apartment.create"]);
                    Route::get("{apartment_check}",        ["as" => "show",    "uses" => "ApartmentCheckController@show"]);
                    Route::delete("multi-delete",   ["as" => "destroyMulti", "uses" => "ApartmentCheckController@destroyMultiple"]);
                    Route::get("{apartment_check}/edit",   ["as" => "edit",    "uses" => "ApartmentCheckController@edit",    "middleware" => "permission:actions.apartment.edit"]);
                    Route::put("{apartment_check}",        ["as" => "update",  "uses" => "ApartmentCheckController@update",  "middleware" => "permission:actions.apartment.edit"]);
                    Route::get("{apartment_check}/delete", ["as" => "destroy", "uses" => "ApartmentCheckController@destroy", "middleware" => "permission:actions.apartment.delete"]);
                });

            });

            /**
             * 'Home Actions' permission routes
             */
            Route::group(['middleware' => ['permission:actions.home*'], 'prefix' => "home", "as" => "home."], function(){

                Route::get('/',             ["as" => "index",   "uses" => "HomeController@index"]);
                Route::get("create",        ["as" => "create",  "uses" => "HomeController@create",  "middleware" => "permission:actions.home.create"]);
                Route::post("/",            ["as" => "store",   "uses" => "HomeController@store",   "middleware" => "permission:actions.home.create"]);
                Route::delete("multi-delete",   ["as" => "destroyMulti", "uses" => "HomeController@destroyMultiple", "middleware" => "permission:actions.home.delete"]);
                Route::get("{home}",        ["as" => "show",    "uses" => "HomeController@show"]);
                Route::get("{home}/edit",   ["as" => "edit",    "uses" => "HomeController@edit",    "middleware" => "permission:actions.home.edit"]);
                Route::put("{home}",        ["as" => "update",  "uses" => "HomeController@update",  "middleware" => "permission:actions.home.edit"]);
                Route::get("{home}/delete", ["as" => "destroy", "uses" => "HomeController@destroy", "middleware" => "permission:actions.home.delete"]);

            });

            /**
             * 'Sell Actions' permission routes
             */
            Route::group(['middleware' => ['permission:actions.sell*'], 'prefix' => "sell", "as" => "sell."], function(){

                Route::get('/',             ["as" => "index",   "uses" => "SellController@index"]);
                Route::get("create",        ["as" => "create",  "uses" => "SellController@create",  "middleware" => "permission:actions.sell.create"]);
                Route::post("/",            ["as" => "store",   "uses" => "SellController@store",   "middleware" => "permission:actions.sell.create"]);
                Route::delete("multi-delete",   ["as" => "destroyMulti", "uses" => "SellController@destroyMultiple", "middleware" => "permission:actions.sell.delete"]);
                Route::get("{sell}",        ["as" => "show",    "uses" => "SellController@show"]);
                Route::get("{sell}/edit",   ["as" => "edit",    "uses" => "SellController@edit",    "middleware" => "permission:actions.sell.edit"]);
                Route::put("{sell}",        ["as" => "update",  "uses" => "SellController@update",  "middleware" => "permission:actions.sell.edit"]);
                Route::get("{sell}/delete", ["as" => "destroy", "uses" => "SellController@destroy", "middleware" => "permission:actions.sell.delete"]);

            });

            Route::group(["as" => "util.", "prefix" => "util"], function(){
                Route::get('apartments', ["as" => "apartments", "uses" => "UtilController@apartments"]);
                Route::get('options', ['as' => 'options', "uses" => "UtilController@options"]);
            });
        });

        /**
         * 'List' permission routes
         */
        Route::group(['middleware' => ['permission:list*'], "prefix" => "list", "as" => "list.", "namespace" => "Index"], function(){

            /**
             * 'Apartment List' permission routes
             */
            Route::group(['middleware' => ['permission:list.apartment*'], 'prefix' => "apartment", "as" => "apartment."], function(){

                Route::get('/',                  ["as" => "index",   "uses" => "ApartmentController@index"]);
                Route::get("{apartment}",        ["as" => "show",    "uses" => "ApartmentController@show"]);
                Route::get("{apartment}/edit",   ["as" => "edit",    "uses" => "ApartmentController@edit",    "middleware" => "permission:list.apartment.edit"]);
                Route::put("{apartment}",        ["as" => "update",  "uses" => "ApartmentController@update",  "middleware" => "permission:list.apartment.edit"]);
                Route::get("{apartment}/delete", ["as" => "destroy", "uses" => "ApartmentController@destroy", "middleware" => "permission:list.apartment.delete"]);

                Route::group(["middleware" => ['permission:list.apartment.check*'], "prefix" => "{apartment}/check", "as" => "check."], function(){
                    Route::get('/',                 ["as" => "index",   "uses" => "ApartmentCheckController@index"]);
                    Route::get("{apartment_check}", ["as" => "show",    "uses" => "ApartmentCheckController@show"]);
                });

            });

            /**
             * 'Home List' permission routes
             */
            Route::group(['middleware' => ['permission:list.home*'], 'prefix' => "home", "as" => "home."], function(){

                Route::get('/',             ["as" => "index",   "uses" => "HomeController@index"]);
                Route::get("{home}",        ["as" => "show",    "uses" => "HomeController@show"]);
                Route::get("{home}/edit",   ["as" => "edit",    "uses" => "HomeController@edit",    "middleware" => "permission:list.home.edit"]);
                Route::put("{home}",        ["as" => "update",  "uses" => "HomeController@update",  "middleware" => "permission:list.home.edit"]);
                Route::get("{home}/delete", ["as" => "destroy", "uses" => "HomeController@destroy", "middleware" => "permission:list.home.delete"]);

            });

            /**
             * 'Sell List' permission routes
             */
            Route::group(['middleware' => ['permission:list.sell*'], 'prefix' => "sell", "as" => "sell."], function(){

                Route::get('/',             ["as" => "index",   "uses" => "SellController@index"]);

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class DashboardController extends Controller
{

    public function index() {
        return view('dashboard.index');
    }

}

resources/views/dashboard/index.blade.php
@extends('layout.page')

@section('title', 'Pano')

@section('plugin.js')
    <script src="{{ asset('assets/global/plugins/counterup/jquery.waypoints.min.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/global/plugins/counterup/jquery.counterup.min.js') }}" type="text/javascript"></script>
@stop

@section('page')
    <!-- BEGIN PAGE HEADER-->
    <!-- BEGIN PAGE BAR -->
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <a href="{{ url('/') }}">{{ config('app.name') }}</a>
                <i class="fa fa-circle"></i>
            </li>
            <li>
                <span>Pano</span>
            </li>
        </ul>
    </div>
    <!-- END PAGE BAR -->
    <!-- BEGIN PAGE TITLE-->
    <h3 class="page-title"> Pano
        <small>pano & genel istatistikler</small>
    </h3>
    <!-- END PAGE TITLE-->
    <!-- END PAGE HEADER-->
    <!-- BEGIN DASHBOARD-->
    <div class="row">
        @permission('actions.apartment')
        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
            <div class="dashboard-stat blue">
                <div class="visual">
                    <i class="fa fa-building"></i>
                </div>
                <div class="details">
                    <div class="number">
                        <span data-counter="counterup" data-value="{{ auth()->user()->apartment_checks->count() }}">0</span>
                    </div>
                    <div class="desc"> Apartman Girişi Yaptınız </div>
                </div>
                <a class="more" href="{{ route('actions.apartment.index') }}"> Tümü
                    <i class="m-icon-swapright m-icon-white"></i>
                </a>
            </div>
        </div>
        @endpermission
        @permission('list.apartment')
        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
            <div class="dashboard-stat blue">
                <div class="visual">
                    <i class="fa fa-building"></i>
                </div>
                <div class="details">
                    <div class="number">
                        <span data-counter="counterup" data-value="{{ \App\ApartmentCheck::count() }}">0</span>
                    </div>
                    <div class="desc"> Apartman Girişi </div>
                </div>
                <a class="more" href="{{ route('list.apartment.index') }}"> Tümü
                    <i class="m-icon-swapright m-icon-white"></i>
                </a>
            </div>
        </div>
        @endpermission
        @permission('actions.home')
        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
            <div class="dashboard-stat red">
                <div class="visual">
                    <i class="fa fa-user"></i>
                </div>
                <div class="details">
                    <div class="number">
                        <span data-counter="counterup" data-value="{{ auth()->user()->homes->count() }}">0</span></div>
                    <div class="desc"> Daire Girişi Yaptınız </div>
                </div>
                <a class="more" href="{{ route('actions.home.index') }}"> Tümü
                    <i class="m-icon-swapright m-icon-white"></i>
                </a>
            </div>
        </div>
        @endpermission
        @permission('list.home')
        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
            <div class="dashboard-stat red">
                <div class="visual">
                    <i class="fa fa-user"></i>
                </div>
                <div class="details">
                    <div class="number">
                        <span data-counter="counterup" data-value="{{ \App\Home::count() }}">0</span></div>
                    <div class="desc"> Daire Girişi </div>
                </div>
                <a class="more" href="{{ route('list.home.index') }}"> Tümü
                    <i class="m-icon-swapright m-icon-white"></i>
                </a>
            </div>
        </div>
        @endpermission
        @permission('actions.sell')
        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
            <div class="dashboard-stat green">
                <div class="visual">
                    <i class="fa fa-shopping-cart"></i>
                </div>
                <div class="details">
                    <div class="number">
                        <span data-counter="counterup" data-value="{{ auth()->user()->sells->count() }}">0</span>
                    </div>
                    <div class="desc"> Satış Yaptınız </div>
                </div>
                <a class="more" href="{{ route('actions.sell.index') }}"> Tümü
                    <i class="m-icon-swapright m-icon-white"></i>
                </a>
            </div>
        </div>
        @endpermission
        @permission('list.sell')
        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
            <div class="dashboard-stat green">
                <div class="visual">
                    <i class="fa fa-shopping-cart"></i>
                </div>
                <div class="details">
                    <div class="number">
                        <span data-counter="counterup" data-value="{{ \App\Sell::count() }}">0</span>
                    </div>
                    <div class="desc"> Satış </div>
                </div>
                <a class="more" href="{{ route('list.sell.index') }}"> Tümü
                    <i class="m-icon-swapright m-icon-white"></i>
                </a>
            </div>
        </div>
        @endpermission
        @permission('manage.users')
        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
            <div class="dashboard-stat purple">
                <div class="visual">
                    <i class="fa fa-male"></i>
                </div>
                <div class="details">
                    <div class="number">
                        <span data-counter="counterup" data-value="{{ App\User::count()  }}">0</span>
                    </div>
                    <div class="desc"> Personel </div>
                </div>
                <a class="more" href="javascript:;"> Tümü
                    <i class="m-icon-swapright m-icon-white"></i>
                </a>
            </div>
        </div>
        @endpermission
    </div>
    <div class="clearfix"></div>
    <!-- END DASHBOARD-->
@stop