routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::model('town', 'App\Town');
Route::model('apartment_check', 'App\ApartmentCheck');

/**
 * Main Route Group
 */
Route::group([], function(){

    /**
     * Public Routes
     */
    // ...

    /**
     * Only Authenticated Users Routes
     */
    Route::group(["middleware" => "auth"], function(){

        // Dashboard Route
        Route::get("/", ["as" => "dashboard.index", "uses" => "DashboardController@index"]);

        /**
         * 'Actions' permission routes
         */
        Route::group(['middleware' => ['permission:actions*'], "prefix" => "action", "as" => "actions.", "namespace" => "Action"], function(){

            // 'Actions Create' route for multiple create actions.
            Route::get('create', ["as" => "create", "middleware" => ['permission:actions.create'], "uses" => "ActionsController@create"]);
            Route::post('create', ["as" => "store", "middleware" => ['permission:actions.create'], "uses" => "ActionsController@store"]);

            /**
             * 'Apartment Actions' permission routes
             */
            Route::group(['middleware' => ['permission:actions.apartment*'], 'prefix' => "apartment", "as" => "apartment."], function(){

                Route::get('/',                  ["as" => "index",   "uses" => "ApartmentController@index"]);
                Route::get("create",             ["as" => "create",  "uses" => "ApartmentController@create",  "middleware" => "permission:actions.apartment.create"]);
                Route::post("/",                 ["as" => "store",   "uses" => "ApartmentController@store",   "middleware" => "permission:actions.apartment.create"]);
                Route::get("{apartment}",        ["as" => "show",    "uses" => "ApartmentController@show"]);
                Route::delete("multi-delete",   ["as" => "destroyMulti", "uses" => "ApartmentController@destroyMultiple"]);
                Route::get("{apartment}/edit",   ["as" => "edit",    "uses" => "ApartmentController@edit",    "middleware" => "permission:actions.apartment.edit"]);
                Route::put("{apartment}",        ["as" => "update",  "uses" => "ApartmentController@update",  "middleware" => "permission:actions.apartment.edit"]);
                Route::get("{apartment}/delete", ["as" => "destroy", "uses" => "ApartmentController@destroy", "middleware" => "permission:actions.apartment.delete"]);

                Route::group(["middleware" => ['permission:actions.apartment.check*'], "prefix" => "{apartment}/check", "as" => "check."], function(){
                    Route::get('/',                  ["as" => "index",   "uses" => "ApartmentCheckController@index"]);
                    Route::get("create",             ["as" => "create",  "uses" => "ApartmentCheckController@create",  "middleware" => "permission:actions.apartment.create"]);
                    Route::post("/",                 ["as" => "store",   "uses" => "ApartmentCheckController@store",   "middleware" => "permission:actions.apartment.create"]);
                    Route::get("{apartment_check}",        ["as" => "show",    "uses" => "ApartmentCheckController@show"]);
                    Route::delete("multi-delete",   ["as" => "destroyMulti", "uses" => "ApartmentCheckController@destroyMultiple"]);
                    Route::get("{apartment_check}/edit",   ["as" => "edit",    "uses" => "ApartmentCheckController@edit",    "middleware" => "permission:actions.apartment.edit"]);
                    Route::put("{apartment_check}",        ["as" => "update",  "uses" => "ApartmentCheckController@update",  "middleware" => "permission:actions.apartment.edit"]);
                    Route::get("{apartment_check}/delete", ["as" => "destroy", "uses" => "ApartmentCheckController@destroy", "middleware" => "permission:actions.apartment.delete"]);
                });

            });

            /**
             * 'Home Actions' permission routes
             */
            Route::group(['middleware' => ['permission:actions.home*'], 'prefix' => "home", "as" => "home."], function(){

                Route::get('/',             ["as" => "index",   "uses" => "HomeController@index"]);
                Route::get("create",        ["as" => "create",  "uses" => "HomeController@create",  "middleware" => "permission:actions.home.create"]);
                Route::post("/",            ["as" => "store",   "uses" => "HomeController@store",   "middleware" => "permission:actions.home.create"]);
                Route::delete("multi-delete",   ["as" => "destroyMulti", "uses" => "HomeController@destroyMultiple", "middleware" => "permission:actions.home.delete"]);
                Route::get("{home}",        ["as" => "show",    "uses" => "HomeController@show"]);
                Route::get("{home}/edit",   ["as" => "edit",    "uses" => "HomeController@edit",    "middleware" => "permission:actions.home.edit"]);
                Route::put("{home}",        ["as" => "update",  "uses" => "HomeController@update",  "middleware" => "permission:actions.home.edit"]);
                Route::get("{home}/delete", ["as" => "destroy", "uses" => "HomeController@destroy", "middleware" => "permission:actions.home.delete"]);

            });

            /**
             * 'Sell Actions' permission routes
             */
            Route::group(['middleware' => ['permission:actions.sell*'], 'prefix' => "sell", "as" => "sell."], function(){

                Route::get('/',             ["as" => "index",   "uses" => "SellController@index"]);
                Route::get("create",        ["as" => "create",  "uses" => "SellController@create",  "middleware" => "permission:actions.sell.create"]);
                Route::post("/",            ["as" => "store",   "uses" => "SellController@store",   "middleware" => "permission:actions.sell.create"]);
                Route::delete("multi-delete",   ["as" => "destroyMulti", "uses" => "SellController@destroyMultiple", "middleware" => "permission:actions.sell.delete"]);
                Route::get("{sell}",        ["as" => "show",    "uses" => "SellController@show"]);
                Route::get("{sell}/edit",   ["as" => "edit",    "uses" => "SellController@edit",    "middleware" => "permission:actions.sell.edit"]);
                Route::put("{sell}",        ["as" => "update",  "uses" => "SellController@update",  "middleware" => "permission:actions.sell.edit"]);
                Route::get("{sell}/delete", ["as" => "destroy", "uses" => "SellController@destroy", "middleware" => "permission:actions.sell.delete"]);

            });

            Route::group(["as" => "util.", "prefix" => "util"], function(){
                Route::get('apartments', ["as" => "apartments", "uses" => "UtilController@apartments"]);
                Route::get('options', ['as' => 'options', "uses" => "UtilController@options"]);
            });
        });

        /**
         * 'List' permission routes
         */
        Route::group(['middleware' => ['permission:list*'], "prefix" => "list", "as" => "list.", "namespace" => "Index"], function(){

            /**
             * 'Apartment List' permission routes
             */
            Route::group(['middleware' => ['permission:list.apartment*'], 'prefix' => "apartment", "as" => "apartment."], function(){

                Route::get('/',                  ["as" => "index",   "uses" => "ApartmentController@index"]);
                Route::get("{apartment}",        ["as" => "show",    "uses" => "ApartmentController@show"]);
                Route::get("{apartment}/edit",   ["as" => "edit",    "uses" => "ApartmentController@edit",    "middleware" => "permission:list.apartment.edit"]);
                Route::put("{apartment}",        ["as" => "update",  "uses" => "ApartmentController@update",  "middleware" => "permission:list.apartment.edit"]);
                Route::get("{apartment}/delete", ["as" => "destroy", "uses" => "ApartmentController@destroy", "middleware" => "permission:list.apartment.delete"]);

                Route::group(["middleware" => ['permission:list.apartment.check*'], "prefix" => "{apartment}/check", "as" => "check."], function(){
                    Route::get('/',                 ["as" => "index",   "uses" => "ApartmentCheckController@index"]);
                    Route::get("{apartment_check}", ["as" => "show",    "uses" => "ApartmentCheckController@show"]);
                });

            });

            /**
             * 'Home List' permission routes
             */
            Route::group(['middleware' => ['permission:list.home*'], 'prefix' => "home", "as" => "home."], function(){

                Route::get('/',             ["as" => "index",   "uses" => "HomeController@index"]);
                Route::get("{home}",        ["as" => "show",    "uses" => "HomeController@show"]);
                Route::get("{home}/edit",   ["as" => "edit",    "uses" => "HomeController@edit",    "middleware" => "permission:list.home.edit"]);
                Route::put("{home}",        ["as" => "update",  "uses" => "HomeController@update",  "middleware" => "permission:list.home.edit"]);
                Route::get("{home}/delete", ["as" => "destroy", "uses" => "HomeController@destroy", "middleware" => "permission:list.home.delete"]);

            });

            /**
             * 'Sell List' permission routes
             */
            Route::group(['middleware' => ['permission:list.sell*'], 'prefix' => "sell", "as" => "sell."], function(){

                Route::get('/',             ["as" => "index",   "uses" => "SellController@index"]);

app/Home.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Home extends Model
{

    public function apartment()
    {
        return $this->belongsTo(Apartment::class);
    }

    public function provider()
    {
        return $this->belongsTo(Provider::class);
    }

    public function pictures()
    {
        return $this->hasMany(HomePicture::class);
    }

    public function sells()
    {
        return $this->hasMany(Sell::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function getHumanCommitmentAttribute()
    {
        if($this->commitment){
            $exp = explode("-", $this->commitment);
            return $exp[2].".".$exp[1].".".$exp[0];
        }
        return null;
    }

    public function getIsLockedAttribute()
    {
        if(auth()->user()->hasRole('yonetici'))
            return false;
        $created = $this->created_at;
        $now     = Carbon::now();

        return $now->diffInMinutes($created) > setting('action_lock');
    }

}

app/Http/Controllers/Action/ActionsController.php
<?php

namespace App\Http\Controllers\Action;

use App\Apartment;
use App\ApartmentCheck;
use App\ApartmentCheckPicture;
use App\Home;
use App\HomePicture;
use App\Http\Requests\Action\ActionCreateRequest;
use App\Sell;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ActionsController extends Controller
{
    public function create()
    {
        return view('action.action.create');
    }

    protected function newApartment($name, $district, $street, $town, $visorName, $visorSurname, $visorPhone) {
        $apartment = new Apartment();
        if($district != "not")
            $apartment->district_id = $district;
        if($street != "not")
            $apartment->street_id = $street;
        if($town != "not")
            $apartment->town_id = $town;
        $apartment->name = $name;
        $apartment->visor_name = $visorName;
        $apartment->visor_surname = $visorSurname;
        $apartment->visor_phone = $visorPhone;
        $apartment->save();

        return $apartment;
    }

    protected function newApartmentCheck($apartment, $notes, $options, $pictures) {
        $check = new ApartmentCheck();
        $check->apartment_id = $apartment;
        $check->user_id = auth()->user()->id;
        $check->notes = $notes;
        $check->save();
        $check->options()->sync($options);

        if($pictures) {
            foreach ($pictures as $pic) {
                $uploadName = str_random(16) . "." . $pic->getClientOriginalExtension();
                $pic->move(public_path('upload/checks/apartment'), $uploadName);
                $uploadPath = "upload/checks/apartment/" . $uploadName;

                $picture = new ApartmentCheckPicture();
                $picture->apartment_check_id = $check->id;
                $picture->name = $pic->getClientOriginalName();
                $picture->file = $uploadPath;
                $picture->save();
            }
        }

        return $check;
    }

    public function store(ActionCreateRequest $request)
    {
        $completed = [
            "apartment" => null,
            "apartmentCheck" => null,
            "homes" => [],
            "sells" => [],
        ];

        $apartmentId = $request->get('apartment_id');
        if(!is_numeric($apartmentId)){
            $apartment = $this->newApartment(
                $request->get('apartment_id'),
                $request->get('district_id'),
                $request->get('street_id'),
                $request->get('town_id'),
                $request->get('visor_name'),
                $request->get('visor_surname'),
                $request->get('visor_phone'));
            $completed['apartment'] = $apartment;
            $apartmentId = $apartment->id;
        }

        $apartmentCheck = $this->newApartmentCheck(
            $apartmentId,
            $request->get('apartment_check_notes'),
            $request->get('apartment_check_option'),
            $request->file('apartment_check_pictures')
        );
        $completed['apartmentCheck'] = $apartmentCheck;

        if($request->has('home') && $request->get('home') && count($request->get('home')) > 0){
        foreach($request->get('home') as $home){
            $commitment = null;
            if($home['commitment']){
                $exp = explode(".", $home['commitment']);
                if(count($exp) == 3){
                    $commitment = $exp[2]."-".$exp[1]."-".$exp[0];
                }
            }

            $homeCheck = new Home();
            $homeCheck->name = $home['name'];
            $homeCheck->surname = $home['surname'];
            $homeCheck->identity = isset($home['identity']) ? $home['identity'] : null;
            $homeCheck->phone = $home['phone'];
            $homeCheck->email = $home['email'];
            $homeCheck->commitment = $commitment;
            $homeCheck->notes = $home['notes'];
            $homeCheck->apartment_id = $apartmentId;
            $homeCheck->provider_id = $home['provider_id'] != "0" ? $home['provider_id'] : null;
            $homeCheck->user_id = auth()->user()->id;
            $homeCheck->home_no = $home['home_no'];
            $homeCheck->save();

            if(isset($home['pictures'])) {
                foreach ($home['pictures'] as $pic) {

                    $uploadName = str_random(16) . "." . $pic->getClientOriginalExtension();
                    $pic->move(public_path('upload/checks/home'), $uploadName);
                    $uploadPath = "upload/checks/home/" . $uploadName;

                    $picture = new HomePicture();
                    $picture->home_id = $homeCheck->id;
                    $picture->name = $pic->getClientOriginalName();
                    $picture->file = $uploadPath;
                    $picture->save();
                }
            }

            if($home['sell'] == 1){

                $sell = new Sell();
                $sell->home_id = $homeCheck->id;
                $sell->campaign_id = $home['campaign_id'] != 0 ? $home['campaign_id'] : null;
                $sell->user_id = auth()->user()->id;
                $sell->save();

                $packageInput = $home['campaign_id'] != 0 ? "campaignPackages" : "packages";
                $sell->packages()->attach($home[$packageInput]);

                $completed['sells'][] = $sell;
            }

            $completed['homes'][] = $homeCheck;
        }
        }
        return view('action.action.success', [
            "apartment" => $completed['apartment'],
            "apartmentCheck" => $completed['apartmentCheck'],
            "homes" => $completed['homes'],
            "sells" => $completed['sells'],
        ]);
    }
}

app/Http/Controllers/Action/UtilController.php
<?php

namespace App\Http\Controllers\Action;

use App\CheckOption;
use App\District;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class UtilController extends Controller
{
    public function apartments(Request $request) {
        $result = [];

        $search = $request->get('search');
        $district = District::find($request->get('district_id'));
        $result["results"] = [];

        if($search)
            $apartments = $district->apartments()->where('name', 'LIKE', '%'.$search.'%')->orderBy('name', 'ASC')->get();
        else
            $apartments = $district->apartments()->orderBy('name', 'ASC')->get();

        foreach($apartments as $apartment){
            $result["results"][] = [
                "text" => $apartment->name,
                "id"   => $apartment->id
            ];
        }

        return $result;
    }

    public function options() {
        return CheckOption::select('id', 'name')->get();
    }
}

resources/views/action/home/index.blade.php
@extends('layout.page')

@section('title', "Daire Girişlerim")

@section('page')
    <!-- BEGIN PAGE HEADER-->
    <!-- BEGIN PAGE BAR -->
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <a href="{{ url('/') }}">{{ config('app.name') }}</a>
                <i class="fa fa-circle"></i>
            </li>
            <li>
                <span>Daire Girişlerim</span>
            </li>
        </ul>
    </div>
    <!-- END PAGE BAR -->
    <!-- END PAGE HEADER-->
    <br>
    <!-- BEGIN TABLE -->
    <div class="row">
        <div class="col-md-12">
            <div class="portlet light bordered">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="icon-social-dribbble font-green"></i>
                        <span class="caption-subject font-green bold uppercase">Daire Girişlerim</span>
                    </div>
                    <div class="actions">
                        @if($homes->count() > 0)
                            @permission('actions.home.delete')
                            <button type="button" class="btn red btn-outline btn-delete-all" data-url="{{ route('actions.home.destroyMulti') }}">
                                <i class="icon-trash"></i>
                                <span class="hidden-480">Seçilileri Sil</span>
                            </button>
                            @endpermission
                        @endif
                        @permission('actions.home.create')
                        <a class="btn green btn-outline" href="{{ route('actions.home.create') }}">
                            <i class="icon-plus"></i>
                            <span class="hidden-480">Yeni Daire Girişi Ekle</span>
                        </a>
                        @endpermission
                    </div>
                </div>
                <div class="portlet-body">
                    @if($homes->count() > 0)
                        <div class="table-scrollable">
                            <table class="table table-hover table-bordered">
                                <thead>
                                <tr>
                                    @permission('actions.home.delete')
                                    <th width="7%">
                                        <label class="table-select-label">
                                            <input type="checkbox" name="selectAll" class="table-select-all">
                                            <span class="hidden-480">Tümünü Seç</span>
                                        </label>
                                    </th>
                                    @endpermission
                                    <th> İlçe / Mahalle / Sokak </th>
                                    <th> Apartman </th>
                                    <th> Ad Soyad </th>
                                    <th> Giriş Tarihi </th>
                                    @if(auth()->user()->can('actions.home.edit') || auth()->user()->can('actions.home.delete') || auth()->user()->can('actions.home.show'))
                                        <th width="45%">İşlemler</th>
                                    @endif
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($homes as $home)
                                    <tr>
                                        @permission('actions.home.delete')
                                        <td><input type="checkbox" name="select[]" value="{{ $home->id }}" class="table-select"></td>
                                        @endpermission
                                        <td>
                                            @if($home->apartment->attachedTown)
                                            <span class="label label-info">{{ $home->apartment->attachedTown->name }}</span>
                                            @endif

                                            @if($home->apartment->attachedStreet)
                                                /
                                            <span class="label label-info">{{ $home->apartment->attachedStreet->name }}</span>
                                            @endif

                                            @if($home->apartment->district)
                                                /
                                                <span class="label label-info">{{ $home->apartment->district->name }}</span>
                                            @endif
                                        </td>
                                        <td>
                                            {{ $home->apartment->name }}
                                        </td>
                                        <td>{{ $home->name." ".$home->surname }}</td>
                                        <td>
                                            {{ $home->created_at->format('d.m.Y H:i') }}
                                        </td>
                                        @if(auth()->user()->can('actions.home.edit') || auth()->user()->can('actions.home.delete') || auth()->user()->can('actions.home.show'))
                                        <td>
                                            @permission('actions.home.show')
                                            <a href="{{ route('actions.home.show', $home->id) }}" class="btn blue btn-sm btn-outline sbold uppercase">
                                                <i class="fa fa-eye"></i> <span class="hidden-480">Görüntüle</span>
                                            </a>
                                            @endpermission

                                            @if(!$home->isLocked)
                                                @permission('actions.home.edit')
                                                <a href="{{ route('actions.home.edit', $home->id) }}" class="btn yellow btn-sm btn-outline sbold uppercase">
                                                    <i class="fa fa-pencil"></i> <span class="hidden-480">Düzenle</span>
                                                </a>
                                                @endpermission

                                                @permission('actions.home.delete')
                                                <a href="{{ route('actions.home.destroy', $home->id) }}" class="btn red btn-sm btn-outline sbold uppercase delete-confirm">
                                                    <i class="fa fa-trash"></i> <span class="hidden-480">Sil</span>
                                                </a>
                                                @endpermission
                                            @endif
                                        </td>
                                        @endif
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>

                        <div class="text-center">
                            {!! $homes->render() !!}
                        </div>
                    @else
                        <div class="alert alert-danger">
                            <p>
                                Henüz bir daire girişi yapılmadı.
                                @permission('actions.home.create')
                                Yeni bir <a href="{{ route('actions.home.create') }}">daire girişi oluştur</a>abilirsiniz.
                                @endpermission
                            </p>
                        </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
    <!-- END TABLE -->
@stop

@section('plugin.js')
    @parent
    <script src="{{ asset('assets/global/plugins/bootbox/bootbox.min.js') }}" type="text/javascript"></script>
@stop

@section('page.js')
    @parent
    <script src="{{ asset('assets/pages/scripts/table-wizard.js') }}"></script>
@stop